# Generated by Django 5.0 on 2024-01-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='element',
            field=models.CharField(default='passes', max_length=30),
            preserve_default=False,
        ),
    ]
