# Generated by Django 4.2.6 on 2023-10-11 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bookings.person",
                    ),
                ),
            ],
            bases=("bookings.person",),
        ),
        migrations.RemoveField(
            model_name="student",
            name="teacher",
        ),
    ]
