# Generated by Django 4.2.6 on 2023-10-09 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_alter_student_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="plan",
            new_name="notes",
        ),
    ]
