# Generated by Django 4.2.6 on 2023-10-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_rename_plan_lesson_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="lesson_date",
            field=models.DateTimeField(),
        ),
    ]
