# Generated by Django 4.2.6 on 2023-10-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0004_lesson_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="duration",
            field=models.IntegerField(default=60),
        ),
    ]
